name: bukulapak
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.2.1
  get: ^4.3.4
  google_fonts: ^2.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/iconApp/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - assets/
flutter_native_splash:

  background_image: "assets/sampul.png"


  android: true
  ios: true
  web: false

